import assert from 'node:assert/strict';
import { readFile, stat } from 'node:fs/promises';
const json = async path => JSON.parse(await readFile(path, 'utf8'));
const manifest = await json('manifest.json');
const pkg = await json('package.json');
const extension = await json('extension/manifest.json');
const versions = await json('versions.json');
assert.match(manifest.id, /^[a-z]+(?:-[a-z]+)*$/);
assert.ok(!manifest.id.includes('obsidian') && !manifest.id.endsWith('plugin'));
assert.match(manifest.version, /^\d+\.\d+\.\d+$/);
assert.equal(pkg.version, manifest.version, 'package 与插件版本必须一致');
assert.equal(extension.version, manifest.version, '浏览器扩展与插件版本必须一致');
assert.equal(versions[manifest.version], manifest.minAppVersion, 'versions.json 缺少当前兼容版本');
assert.equal(manifest.isDesktopOnly, true);
assert.ok(manifest.description.length <= 250 && manifest.description.endsWith('.'));
if (process.env.RELEASE_TAG) assert.equal(process.env.RELEASE_TAG, manifest.version, '发布 tag 必须与 manifest 完全一致，不加 v');
const directory = `dist/${manifest.id}`;
for (const name of ['manifest.json', 'main.js', 'styles.css']) assert.ok((await stat(`${directory}/${name}`)).size > 0);
assert.deepEqual(await json(`${directory}/manifest.json`), manifest);
assert.equal(await readFile(`${directory}/styles.css`, 'utf8'), await readFile('styles.css', 'utf8'));
assert.ok((await readFile('LICENSE', 'utf8')).startsWith('MIT License'));
const bundle = await readFile(`${directory}/main.js`, 'utf8');
assert.ok(bundle.includes('MIT License') && bundle.includes('Copyright (c) 2026 zhangxun-ai'), '安装文件必须保留项目 MIT 许可');
assert.ok(bundle.includes('Copyright Eemeli Aro') && bundle.includes('THE AUTHOR DISCLAIMS ALL WARRANTIES'), '安装文件必须保留 yaml 的 ISC 版权与许可');
assert.ok(!bundle.includes('/Users/'), '发行包不得含本机个人路径');
for(const size of [16,32,48,128]){
  const icon=await readFile(`extension/${extension.icons[size]}`);
  assert.equal(icon.subarray(0,8).toString('hex'),'89504e470d0a1a0a');
  assert.equal(icon.readUInt32BE(16),size);assert.equal(icon.readUInt32BE(20),size);
}
const archive=await readFile(`dist/social-publisher-browser-${manifest.version}.zip`);
assert.equal(archive.readUInt32LE(0),0x04034b50);
assert.equal(archive.readUInt32LE(archive.length-22),0x06054b50);
assert.equal(archive.readUInt16LE(archive.length-12),12,'仅包含扩展运行文件、图标与许可证');
console.log(`发行检查通过：${manifest.id} ${manifest.version}，三个独立安装文件有效。`);
